---
title: "Assignment 8"
author: "Jack Eschert"
date: "2023-01-31"
output: html_document
---

1a. (My code with comments regarding the posted solution)
```{r}
library(tidyverse)
str(iris)
view(iris)
# same as solution
```

```{r}
data(iris)
iris1 <- filter(iris, Species == c("virginica", "versicolor") & Sepal.Width>2.5 & Sepal.Length>6)
iris1

#giving it a vector that's a different length therefore must use in operator otherwise it'll do something else. == and %in% do similar things but == must have the same vector lengths, %in% knows the vector is of a smaller length and it checks each element of species and sees if located in new vector and locates that way, to use == must speperate the 2 species via | , or 

# correct code:


```

```{r}
iris2 <- select(iris1, -c(Petal.Length, Petal.Width))
str(iris2)
glimpse(iris2)

# same result in terms of number of columns as proper code but inaccurate number of observations due to error for iris1


```

```{r}
iris3 <- arrange(iris2, by=desc(Sepal.Length))
head(iris3)

# correct code as answer key but inaccurate order of Sepal.Length due to error in iris1
```

```{r}
iris4 <- mutate(iris3, Sepal.Area=Sepal.Length*Sepal.Width)
str(iris4)

# correct code and number of variables as answer key but incorrect number of observations due to cascading error from iris1

```

```{r}
irisTab <- summarize(iris4, Average.Sepal.Length = mean(Sepal.Length), Average.Sepal.Width=mean(Sepal.Width), TotalNumber=n())
irisTab

# same code as answer key but incorrect number of observations due to previous error 


```

```{r}
IrisSpecies <- group_by(iris4, Species)
iris5 <- summarize(IrisSpecies, Average.Sepal.Length = mean(Sepal.Length), Average.Sepal.Width=mean(Sepal.Width), TotalNumber=n())
print(iris5)

# same code as asnwer key but incorrect data due to previous error 
```

```{r}
irisFinal <- iris %>%
  filter(Species == c("virginica", "versicolor") & Sepal.Width>2.5 & Sepal.Length>6) %>%
  select(-c(Petal.Length, Petal.Width)) %>%
  arrange(by=desc(Sepal.Length)) %>%
  mutate(Sepal.Area=Sepal.Length*Sepal.Width) %>%
  group_by(Species) %>%
  summarize(Average.Sepal.Length = mean(Sepal.Length), Average.Sepal.Width=mean(Sepal.Width), TotalNumber=n())
irisFinal

# all is correct except for the first line of the piping which uses == as opposed to %in% which as mentioned before will not work here 
# do I need to have by= in this code? 
```
1b.
```{r}

### NOTE: I struggled alot with Weekly Assignment 2 and consulted both Professor Ash during her office hours and the posted solutions (with her permission) since my original code did not even run, thus the reflection process will not be as rich as that for Assignment 6

## My original thought process
library(tidyverse)
cont <- "Control"
type1 <- rep(cont, 25)
type1
treat <- "Treatment"
type2 <- rep(treat, 25)
type2
Type <- c(type1, type2)
Type

valu1 <- rnorm(n=25, mean=10, sd=1.5)
valu1
valu2 <- rnorm(n=25, mean=45, sd=2)
valu2
Value <- c(valu1, valu2)
Value

dataFrame <- data.frame(Type, Value)
dataFrame

## Final working function 
set.seed(33)
datafram <- function(meana=10, sda=1.5, meanb=45, sdb=2, n=25){
  Type <- c(rep("Control", n), rep("Treatment", n)) 
            Value <- c(rnorm(mean = meana, sd =sda, n=n), rnorm(mean=meanb, sd=sdb, n=n))
            dataFram <- data.frame(Type, Value)
            return(dataFram)
}

datafram()
# to change the parameters paste into ()s of datafram and modify 

# my code is nearly identical to the posted solution because I worked with Professor Ash and the posted solution to reach a functioning code 
```

Altering inputs to see if I 


```{r}
data <- datafram()
head(data)

# correct as posted answer without consultation
```


```{r}
?aov
anova <- aov(Value ~ Type, data = data)
summary(anova)

# correct as posted answer without consultation
```

```{r}
#put ANOVA code within the function, put in any simulated data frame have only one function and have the variables be type and value 
# don't use default variable within code otherwise not producible, make sure to use the argument variable within the code
# # vector after subsetting therefore just say want first element no longer 2d with row and column like a data frame
#View(summary(anova))

# code for extracting the p value


p <- function(datframm = data){
  av <- aov(datframm[,2] ~ datframm[,1], data = datframm)
    summ <- summary(av)
  answer <- summ[[1]][["Pr(>F)"]][1]
  return(answer)
}
p()
```
```{r}
p(datafram())

# here, I worked with Professor Ash to come up with this function. I learned that the extra [1] allows line 150 to extract the first element from the p-value vector since it is no longer in the data frame format. I also learned that I could call the columns of data I wanted to work with by index rather than the names of the columns as I did in line 148. 
```


2. 
```{r}
## Set up libraries
library(tidyverse)
library(ggthemes)


# Data obtained from Veysey Powell and Babbitt 2016: An experimental test of buffer utility as a technique for managing pool-breeding amphibians https://datadryad.org/stash/dataset/doi:10.5061%2Fdryad.547rp

dryadData <- read.table("Data/veysey-babbitt_data_amphibians.csv", header=TRUE, sep=",", stringsAsFactors = TRUE)

# glimpse(dryadData)
# head(dryadData)
# table(dryadData$species)

dryadData$species<-factor(dryadData$species, labels=c("Spotted Salamander", "Wood Frog")) #creating 'labels' to use for the plot

#class(dryadData$treatment)
dryadData$treatment <- factor(dryadData$treatment, 
            levels=c("Reference",
                     "100m", "30m"))


p<- ggplot(data=dryadData, # assinging the variable p to the function that will generate the desired plot, specifying that the data we should be working with is the Dryad data
       aes(x=interaction(wetland, treatment), # aes() evaluates the inputs in the context of the data, specifies the x-variable 
           y=count.total.adults, fill=factor(year))) + geom_bar(position="dodge", stat="identity", color="black") + # specifies the y-variable and fills in the bars to distinguish by year via fill(), the factor() fcn works with categorical variables to help plot them
  # geom_bar specifies we want a bar plot, 
  # position="dodge" preserves the vertical position of the data while  adjusting the horizontal position of the bars, 
  # stat="identity" tells R to calculate the sum of the y-variable grouped by the x-variable and to use bars to display them
  # color="black" tells the plot to have black-bordered columns 
  ylab("Number of breeding adults") + # specifies the y-label for the plot
  xlab("") + # empty () indicates no x-label for the plot is specified
  scale_y_continuous(breaks = c(0,100,200,300,400,500)) + # specifies the interval/scale for the y-axis
  scale_x_discrete(labels=c("30 (Ref)", "124 (Ref)", "141 (Ref)", "25 (100m)","39 (100m)","55 (100m)","129 (100m)", "7 (30m)","19 (30m)","20 (30m)","59 (30m)")) + # sepcifeies the interval/scale for the x-axis 
  facet_wrap(~species, nrow=2, strip.position="right") + 
  theme_few() + scale_fill_grey() + # theme for the plots overall appearance is them_few()
  # scale_fill_grey() indicates that grey colors should fill the bar columns 
  theme(panel.background = element_rect(fill = 'gray94', color = 'black'), # elements about the 
        legend.position="top",  legend.title= element_blank(), axis.title.y = element_text(size=12, face="bold", colour = "black"), 
        strip.text.y = element_text(size = 10, face="bold", colour = "black"))  # let's the scale be all in one line rather than on top

p
```

