---
title: "Weekly Assignment 2"
author: "Jack Eschert"
date: "2023-01-19"
output: html_document
---
1.
```{r}

## My original thought process
library(tidyverse)
cont <- "Control"
type1 <- rep(cont, 25)
type1
treat <- "Treatment"
type2 <- rep(treat, 25)
type2
Type <- c(type1, type2)
Type

valu1 <- rnorm(n=25, mean=10, sd=1.5)
valu1
valu2 <- rnorm(n=25, mean=45, sd=2)
valu2
Value <- c(valu1, valu2)
Value

dataFrame <- data.frame(Type, Value)
dataFrame

## Final working function 
set.seed(33)
datafram <- function(meana=10, sda=1.5, meanb=45, sdb=2, n=25){
  Type <- c(rep("Control", n), rep("Treatment", n)) 
            Value <- c(rnorm(mean = meana, sd =sda, n=n), rnorm(mean=meanb, sd=sdb, n=n))
            dataFram <- data.frame(Type, Value)
            return(dataFram)
}

datafram()
# to change the parameters paste into ()s of datafram and modify 
```
2. 
```{r}
data <- datafram()
head(data)

```

3. 
```{r}
?aov
anova <- aov(Value ~ Type, data = data)
summary(anova)
```
4.
```{r}
#put ANOVA code within the function, put in any simulated data frame have only one function and have the variables be type and value 
# don't use default variable within code otherwise not producible, make sure to use the argument variable within the code
# # vector after subsetting therefore just say want first element no longer 2d with row and column like a data frame
#View(summary(anova))

# code for extracting the p value


p <- function(datframm = data){
  av <- aov(datframm[,2] ~ datframm[,1], data = datframm)
    summ <- summary(av)
  answer <- summ[[1]][["Pr(>F)"]][1]
  return(answer)
}
p()
```
```{r}
p(datafram())
```



